#!/usr/bin/perl -w
#
# Copyright (c) 2022 Adrian Schroeter, SUSE LLC
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program (see the file COPYING); if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#
################################################################
#
# OBS Git LFS provider
# 
# This service answers git LFS requests and let OBS deliver the files
# based on a static database.
#
# This is only supposed to be used for converted sources from classic
# OBS source repositories. This is not supposed to be used for sources
# which are supposed to be actively maintained in git directly.
#

BEGIN {
  my ($wd) = $0 =~ m-(.*)/- ;
  $wd ||= '.';
  unshift @INC,  "$wd";
}

use Data::Dumper;
use JSON::XS ();
use MIME::Base64 ();

use BSServer;
use BSRPC ':https';
use BSDispatch;
use BSXML;
use BSPreset;

use strict;

my $port = 9998;
my $proto = 'http';

my $obsurl = "https://api.opensuse.org/public";
my $header = "X-SCM-BRIDGE-COOKIE: not_configured";
my $queue_dir = "/srv/obs-gitea-bridge/queue";
my $gitea_root = "/var/lib/gitea/data";
my $autosetup_prefix;
my $api_username;
my $api_password;
eval {
  use config;
  $header = "X-SCM-BRIDGE-COOKIE: $config::shared_cookie" if $config::shared_cookie;
  $obsurl = $config::obsurl;
  $queue_dir = $config::queue_dir if $config::queue_dir;
  $gitea_root = $config::gitea_root if $config::gitea_root;
  $autosetup_prefix = $config::autosetup_prefix if $config::autosetup_prefix;
  $api_username = $config::api_username if defined $config::api_username;
  $api_password = $config::api_password if defined $config::api_password;
};

# OBS api base url without a trailing /public marker, used for the
# authenticated project meta operations below.
(my $source_url = $obsurl) =~ s{/public$}{};

# HTTP Basic Auth header for project meta create/delete operations.
my $api_auth;
if (defined $api_username && defined $api_password) {
  $api_auth = 'Authorization: Basic '.MIME::Base64::encode_base64("$api_username:$api_password", '');
}

# Fetch the download base url from the OBS api at startup and use it as
# the prefix stripped from repo urls when deriving the OBS path
# project/repository. Only needed for the analysing http server.
eval {
  my $body = BSRPC::rpc({ 'uri' => "$obsurl/configuration",
                          'request' => 'GET',
                          'headers' => [$header],
                          'timeout' => 30 }, undef);
  my ($download_url) = ($body =~ m{<download_url>\s*([^<]+?)\s*</download_url>});
  $BSPreset::gitprefix = $download_url if defined $download_url && length $download_url;
  print "using download_url $BSPreset::gitprefix\n";
} unless @ARGV;
print "failed to read download_url from $obsurl/configuration: $@\n" if $@;

sub repositoryresults {
  my ($cgi) = @_;

  my $scmrepo = $cgi->{'scmrepository'};
  my $scmbranch = $cgi->{'scmbranch'};

  my $query = {'scmrepository' => $scmrepo,
	       'scmbranch'     => $scmbranch };
  my @args = BSRPC::args($query, 'scmrepository', 'scmbranch');
  my $r = BSRPC::rpc({'uri' => "$obsurl/build/_result",
	              'request' => 'GET',
	              'headers' => [$header]},
                      $BSXML::resultlist,
                     @args);

  my $html = '<table> <tr> <th>Project</th><th>Package</th> <th>Repository</th> <th>Architecture</th> <th>Result</th> </tr>';
  my $lastproject = '';
  my $lastpackage = '';
  my $lastrepo = '';
  my $count = 0;
  for my $result (@{$r->{'result'} || []}) {
    my $project = $result->{'project'};
    my $package = $result->{'status'}[0]->{'package'} || undef;
    my $repo    = $result->{'repository'};
    my $arch    = $result->{'arch'};
    my $code    = $result->{'status'}[0]->{'code'} || 'unknown';

    $project = '' if $project eq $lastproject;
    $package = '' if $package eq $lastpackage;
    $repo = ''    if $repo eq $lastrepo;
    $count = $count + 1;

    my $bgcolor = "#fff";
    $bgcolor = "#bbb" if $code eq 'scheduled' || $code eq 'building' ||  $code eq 'finished' || $code eq 'blocked';
    my $color = "#FFF";
    $color = "#6EB927" if $code eq 'succeeded';
    $color = "#666" if $code eq 'signing';
    $color = "#222" if $code eq 'finished';
    $color = "#c00" if $code eq 'unresolvable';
    $color = "#e00" if $code eq 'broken';
    $color = "#f00" if $code eq 'failed';
    $color = "#fff" if $code eq 'blocked';

    $html .= "<tr><td>$project</td><td>$package</td> <td>$repo</td> <td>$arch</td> <td bgcolor=\"$bgcolor\"><font color=\"$color\">$code</font></td> </tr>\n";

    $lastproject = $project unless $project eq '' ;
    $lastpackage = $package unless $package eq '' ;
    $lastrepo    = $repo    unless $repo eq '';
    last if $count > 10;
  };
  $html .= '</table>';
  $html .= '<p>.... uncollapsing not implemeted...</p>' if $count > 10;
  return $html;
}

sub gitref_to_branch {
  my ($ref) = @_;
  return undef unless defined $ref;
  $ref =~ s/^refs\/heads\///;
  $ref =~ s/^refs\/tags\///;
  $ref =~ s/^refs\///;
  return $ref;
}

# Read the given file from the given branch of a git repository. Returns
# undef when the repository or the file does not exist (git's error output
# is suppressed).
sub git_show {
  my ($gitdir, $branch, $file) = @_;
  my $pid = open(my $fh, '-|');
  if (!defined $pid) {
    die("cannot fork: $!\n");
  }
  if ($pid == 0) {
    open(STDERR, '>', '/dev/null');
    exec('git', "--git-dir=$gitdir", 'show', "$branch:$file");
    exit 255;
  }
  my $data = do { local $/; <$fh> };
  close($fh);
  return undef if ($? >> 8) != 0;
  return $data;
}

sub process_queue {
  return unless -d $queue_dir;

  opendir(DIR_HANDLE, $queue_dir) or return;
  my @files = sort grep { /^\d+\.json$/ } readdir(DIR_HANDLE);
  closedir(DIR_HANDLE);
  return unless @files;

  for my $file (@files) {
    my $filepath = "$queue_dir/$file";
    my $content = do { local $/; open(my $fh, '<', $filepath) or next; binmode($fh); <$fh> };
    my $batch = JSON::XS::decode_json($content);
    next unless $batch && $batch->{'ref'} && $batch->{'repository'}->{'clone_url'};

    my $branch = gitref_to_branch($batch->{'ref'});

    my $fullname = $batch->{'repository'}->{'full_name'};
    if ($fullname && defined $autosetup_prefix) {
      my $gitdir = "$gitea_root/gitea-repositories/" . lc($fullname) . ".git";
      my $manifest = git_show($gitdir, $branch, '_manifest');
      if (defined $manifest) {
        my ($org, $repo) = split('/', $fullname, 2);
        if (!defined $org || !defined $repo) {
          print "setup_project: cannot determine org/repo from $fullname\n";
        } else {
          $org =~ s/:/_/g;
          $repo =~ s/:/_/g;
          my $scmsync = "$batch->{'repository'}->{'clone_url'}#$branch";
          eval {
            setup_project($manifest, "$autosetup_prefix:$org:$repo:$branch", $batch, $scmsync);
          };
          print "setup_project: failed: $@" if $@;
        }
      }
    }

    my $cgi = { 'cmd'           => 'triggerscmsync',
		'scmrepository' => $batch->{'repository'}->{'clone_url'},
		'scmbranch'     => $branch };
    $cgi->{'isdefaultbranch'} = 1 if $batch->{'repository'}->{'default_branch'} eq $branch;
    my @args = BSRPC::args($cgi, 'cmd', 'scmrepository', 'scmbranch', 'isdefaultbranch');

    eval {
      my $h = BSRPC::rpc({ 'uri' => "$obsurl/source",
      		  	   'request' => 'POST',
      		  	   'headers' => [$header],
      		  	   'timeout' => 30 }, undef, @args);
    };
    if ($@) {
      print "Queue: failed to process $file: $@\n";
      last;
    } else {
      unlink($filepath) or print "Queue: failed to delete $filepath: $!\n";
      print "Processed: $batch->{'repository'}->{'clone_url'}#$branch from $file\n";
    }
  }
}

sub setup_project {
  my ($manifest, $projectname, $batch, $scmsync) = @_;
  my $presets = eval { BSPreset::manifest_presets($manifest) };
  if ($@) {
    print "setup_project: $@";
    return;
  }
  if ($presets && @$presets) {
    create_or_update_project($projectname, $presets, $batch, $scmsync);
  } else {
    delete_project($projectname);
  }
}

sub delete_project {
  my ($projectname) = @_;
  print "delete_project: deleting project $projectname\n";
  my @hdrs = defined $api_auth ? ($api_auth) : ();
  eval {
    BSRPC::rpc({ 'uri' => "$source_url/source/$projectname/_meta",
    		  	   'request' => 'DELETE',
    		  	   'headers' => \@hdrs,
    		  	   'timeout' => 30 }, undef);
  };
  print "delete_project: failed to delete $projectname: $@\n" if $@;
}

sub create_or_update_project {
  my ($projectname, $presets, $batch, $scmsync) = @_;

  my $extrapaths = parent_project_paths($projectname, $presets, $batch);
  my $xml = eval { BSPreset::preset_xml($projectname, $presets, $extrapaths, $scmsync) };
  if ($@) {
    print "create_or_update_project: cannot build project xml for $projectname: $@\n";
    return;
  }
  print "create_or_update_project: project xml for $projectname:\n$xml";

  my @hdrs = ('Content-Type: text/xml');
  push @hdrs, $api_auth if defined $api_auth;
  eval {
    BSRPC::rpc({ 'uri' => "$source_url/source/$projectname/_meta",
    		  	   'request' => 'PUT',
    		  	   'headers' => \@hdrs,
    		  	   'timeout' => 30,
    		  	   'data' => $xml }, undef);
  };
  print "create_or_update_project: failed to update $projectname: $@\n" if $@;
}

# Read the project meta of $projectname from the OBS api.
sub get_project_meta {
  my ($projectname) = @_;
  my @hdrs = defined $api_auth ? ($api_auth) : ();
  my $meta;
  eval {
    $meta = BSRPC::rpc({ 'uri' => "$source_url/source/$projectname/_meta",
    		  	   'request' => 'GET',
    		  	   'headers' => \@hdrs,
    		  	   'timeout' => 30 },
    		  	   $BSXML::proj);
  };
  return ($meta, $@);
}

# If the git repository was forked from another one, look up the upstream
# project (PREFIX:ORG:REPO:BRANCH) in OBS and return additional path entries
# for each preset repository that points into it. Same-project path entries
# of the upstream repositories are replicated pointing at the new project.
# Returns undef when the repository is not a fork or the upstream project
# does not exist.
sub parent_project_paths {
  my ($projectname, $presets, $batch) = @_;
  return undef unless ref($batch) eq 'HASH' && defined $autosetup_prefix;
  my $parent = $batch->{'repository'}{'parent'};
  return undef unless ref($parent) eq 'HASH' && $parent->{'full_name'};
  my ($p_org, $p_repo) = split('/', $parent->{'full_name'}, 2);
  return undef unless defined $p_org && defined $p_repo;
  my $branch = gitref_to_branch($batch->{'ref'});
  return undef unless defined $branch;
  $p_org =~ s/:/_/g;
  $p_repo =~ s/:/_/g;
  my $parent_project = "$autosetup_prefix:$p_org:$p_repo:$branch";
  my ($pmeta, $err) = get_project_meta($parent_project);
  if ($err) {
    print "create_or_update_project: upstream project $parent_project not found, building $projectname without extra paths: $err";
    return undef;
  }
  my $extrapaths = BSPreset::extrapaths_from_parent_meta($projectname, $presets, $pmeta, $parent_project);
  if ($extrapaths) {
    print "create_or_update_project: building $projectname against upstream project $parent_project\n";
  }
  return $extrapaths;
}

# Derive the owner/repo full name from a git url.
sub giturl_to_fullname {
  my ($url) = @_;
  return undef unless defined $url;
  my $path;
  if ($url =~ m{^(?:https?|ssh|git)://[^/]+/(.+)$}) {
    $path = $1;
  } elsif ($url =~ m{^[^@/]+@[^:]+:(.+)$}) {
    $path = $1;
  } else {
    return undef;
  }
  $path =~ s/\.git$//;
  $path =~ s{/+$}{};
  return $path;
}

# Resolve a "GIT_URL#BRANCH" spec into the project name and the manifest
# content taken from the given branch.
sub resolve_project_spec {
  my ($spec) = @_;
  my ($giturl, $branch) = split(/#/, $spec, 2);
  die("invalid '$spec', expected GIT_URL#BRANCH_NAME\n")
    unless defined $giturl && length $giturl && defined $branch && length $branch;
  $branch = gitref_to_branch($branch);
  die("invalid '$spec', expected GIT_URL#BRANCH_NAME\n") unless defined $branch;
  my $fullname = giturl_to_fullname($giturl);
  die("cannot determine org/repo from git url '$giturl'\n") unless defined $fullname;
  die("autosetup_prefix is not configured\n") unless defined $autosetup_prefix;

  my $gitdir = "$gitea_root/gitea-repositories/" . lc($fullname) . ".git";
  my $manifest = git_show($gitdir, $branch, '_manifest');
  die("cannot read _manifest from $giturl#$branch\n") unless defined $manifest;

  my ($org, $repo) = split('/', $fullname, 2);
  die("cannot determine org/repo from $fullname\n") unless defined $org && defined $repo;
  $org =~ s/:/_/g;
  $repo =~ s/:/_/g;
  return ("$autosetup_prefix:$org:$repo:$branch", $manifest, "$giturl#$branch");
}

# Set up a single project for a given git branch, given as "GIT_URL#BRANCH".
sub setup_single_project {
  my ($spec) = @_;
  my ($projectname, $manifest, $scmsync) = resolve_project_spec($spec);
  setup_project($manifest, $projectname, undef, $scmsync);
}

# Print the project meta xml for a given git branch, given as "GIT_URL#BRANCH".
sub show_single_project {
  my ($spec) = @_;
  my ($projectname, $manifest, $scmsync) = resolve_project_spec($spec);
  my $presets = eval { BSPreset::manifest_presets($manifest) };
  die("cannot parse _manifest: $@") if $@;
  if ($presets && @$presets) {
    print BSPreset::preset_xml($projectname, $presets, undef, $scmsync);
  } else {
    print "no project configured for $spec\n";
  }
}

sub repositoryevent {
  die("need event data as content\n") unless BSServer::have_content();
  my $batch_json = BSServer::read_data(10000000);
  my $batch = JSON::XS::decode_json($batch_json);

  die("no ref given\n") unless $batch->{'ref'};
  die("no repository given\n") unless $batch->{'repository'};
  die("no clone repository given\n") unless $batch->{'repository'}->{'clone_url'};

  # write event to queue file
  my $timestamp = time();
  my $filepath = "$queue_dir/$timestamp.json";
  open(my $fh, '>', $filepath) or die("cannot write queue file $filepath: $!\n");
  binmode($fh);
  print $fh $batch_json;
  close($fh);

  # try to process queue
  process_queue();

  my $resp = {
    answer => 'thank you',
  };
  #  print Dumper(JSON::XS::encode_json($resp));
  # print "Received: $filepath\n";
  return (JSON::XS::encode_json($resp), 'Content-Type: application/json');
}

sub hello {
  return ("{\"message\": \"OBS Gitea Bridge\"}\n", 'Content-Type: application/json');
}

sub errorreply {
  my ($err, $code, $tag, @hdrs) = @_;
  $err = JSON::XS::encode_json({'message' => $tag});
  BSServer::reply("$err\n", "Status: $code $tag", 'Content-Type: application/json', @hdrs);
}

sub dispatch {
  my ($conf, $req) = @_;
  return BSDispatch::dispatch($conf, $req);
}

# define server
my $dispatches = [
  '/' => \&hello,
  'GET:/repositoryresults scmrepository:? scmbranch:? code:? lastbuild:? multibuild:? locallink:?' => \&repositoryresults,
  'POST:/repositoryevent' => \&repositoryevent,
];

my $conf = {
  'port' => $port,
  'proto' => $proto,
  'dispatch' => \&dispatch,
  'dispatches' => $dispatches,
  'errorreply' => \&errorreply,
  'setkeepalive' => 1,
  'maxchild' => 20,
};

# single-shot mode: setup or show a single project for a given git branch,
# then exit without starting the server
if (@ARGV) {
  if ($ARGV[0] eq '--setup-project') {
    die("usage: $0 --setup-project GIT_URL#BRANCH_NAME\n") unless $ARGV[1];
    setup_single_project($ARGV[1]);
    exit(0);
  }
  if ($ARGV[0] eq '--show-project') {
    die("usage: $0 --show-project GIT_URL#BRANCH_NAME\n") unless $ARGV[1];
    show_single_project($ARGV[1]);
    exit(0);
  }
  die("unknown option $ARGV[0], usage: $0 [--setup-project GIT_URL#BRANCH_NAME | --show-project GIT_URL#BRANCH_NAME]\n");
}

# ensure queue directory exists
mkdir($queue_dir) or die("cannot create queue directory $queue_dir: $!\n") unless -d $queue_dir;

# process any leftover events from previous run
process_queue();

BSDispatch::compile($conf);
BSServer::serveropen($conf->{'port'});
BSServer::server($conf);
